MeslekOdalariWebUI/Controllers/AboutController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.AboutDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;
        private readonly IMapper _mapper;

        public AboutController(IMapper mapper, IAboutService aboutService)
        {
            _mapper = mapper;
            _aboutService = aboutService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _aboutService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultAboutDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteAbout(ObjectId id)
        {
            await _aboutService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateAbout()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAbout(CreateAboutDto createAboutDto)
        {
            var newValue = _mapper.Map<About>(createAboutDto);
            await _aboutService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateAbout(ObjectId id)
        {
            var value = await _aboutService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateAboutDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAbout(UpdateAboutDto updateAboutDto)
        {
            var updateValue = _mapper.Map<About>(updateAboutDto);
            await _aboutService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Controllers/BoardController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.BoardDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class BoardController : Controller
    {
        private readonly IBoardService _boardService;
        private readonly IMapper _mapper;

        public BoardController(IMapper mapper, IBoardService boardService)
        {
            _mapper = mapper;
            _boardService = boardService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _boardService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultBoardDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteBoard(ObjectId id)
        {
            await _boardService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateBoard()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBoard(CreateBoardDto createBoardDto)
        {
            var newValue = _mapper.Map<Board>(createBoardDto);
            await _boardService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateBoard(ObjectId id)
        {
            var value = await _boardService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateBoardDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBoard(UpdateBoardDto updateBoardDto)
        {
            var updateValue = _mapper.Map<Board>(updateBoardDto);
            await _boardService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Controllers/DateController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.DateDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class DateController : Controller
    {
        private readonly IDateService _dateService;
        private readonly IMapper _mapper;

        public DateController(IMapper mapper, IDateService dateService)
        {
            _mapper = mapper;
            _dateService = dateService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _dateService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultDateDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteDate(ObjectId id)
        {
            await _dateService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateDate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateDate(CreateDateDto createDateDto)
        {
            var newValue = _mapper.Map<Date>(createDateDto);
            await _dateService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateDate(ObjectId id)
        {
            var value = await _dateService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateDateDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateDate(UpdateDateDto updateDateDto)
        {
            var updateValue = _mapper.Map<Date>(updateDateDto);
            await _dateService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeslekOdalariWebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MeslekOdalariWebUI/Controllers/NewsController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.NewsDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsService _newsService;
        private readonly IMapper _mapper;

        public NewsController(IMapper mapper, INewsService newsService)
        {
            _mapper = mapper;
            _newsService = newsService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _newsService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultNewsDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteNews(ObjectId id)
        {
            await _newsService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateNews()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateNews(CreateNewsDto createNewsDto)
        {
            var newValue = _mapper.Map<News>(createNewsDto);
            await _newsService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateNews(ObjectId id)
        {
            var value = await _newsService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateNewsDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateNews(UpdateNewsDto updateNewsDto)
        {
            var updateValue = _mapper.Map<News>(updateNewsDto);
            await _newsService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Views/Shared/Components/_AdminSidebar/Default.cshtml
<div class="quixnav">
    <div class="quixnav-scroll">
        <ul class="metismenu" id="menu">
            <li class="nav-label first">Admin Paneli</li>

            <li>
                <a asp-controller="Banner" asp-action="Index">
                    <i class="fa fa-image"></i>
                    <span class="nav-text">Banner</span>
                </a>
            </li>

            <li>
                <a asp-controller="Contact" asp-action="Index">
                    <i class="fa fa-envelope"></i>
                    <span class="nav-text">İletişim Bilgisi</span>
                </a>
            </li>

            <li>
                <a asp-controller="Counter" asp-action="Index">
                    <i class="fa fa-calculator"></i>
                    <span class="nav-text">Sayaç</span>
                </a>
            </li>

            <li>
                <a asp-controller="Feature" asp-action="Index">
                    <i class="fa fa-list"></i>
                    <span class="nav-text">Öne Çıkanlar</span>
                </a>
            </li>

            <li>
                <a asp-controller="Project" asp-action="Index">
                    <i class="fa fa-folder "></i>
                    <span class="nav-text">Projeler</span>
                </a>
            </li>

            <li>
                <a asp-controller="Regulation" asp-action="Index">
                    <i class="fa fa-gavel"></i>
                    <span class="nav-text">Mevzuat</span>
                </a>
            </li>

            <li>
                <a asp-controller="Board" asp-action="Index">
                    <i class="fa fa-sitemap"></i>
                    <span class="nav-text">Yönetim Kurulu</span>
                </a>
            </li>

            <li>
                <a asp-controller="AuditBoard" asp-action="Index">
                    <i class="fa fa-shield"></i>
                    <span class="nav-text">Denetim Kurulu</span>
                </a>
            </li>

            <li>
                <a asp-controller="DisciplinaryBoard" asp-action="Index">
                    <i class="fa fa-gavel"></i>
                    <span class="nav-text">Disiplin Kurulu</span>
                </a>
            </li>

            <li>
                <a asp-controller="About" asp-action="Index">
                    <i class="fa fa-info-circle"></i> 
                    <span class="nav-text">Hakkımızda</span>
                </a>
            </li>

            <li>
                <a asp-controller="VisionMission" asp-action="Index">
                    <i class="fa fa-eye"></i> <!-- "lightbulb" yerine alternatif -->
                    <span class="nav-text">Vizyon&Misyon</span>
                </a>
            </li>


            <li>
                <a asp-controller="History" asp-action="Index">
                    <i class="fa fa-university"></i> <!-- "landmark" yerine alternatif -->
                    <span class="nav-text">Tarihçemiz</span>
                </a>
            </li>

            <li>
                <a asp-controller="Date" asp-action="Index">
                    <i class="fa fa-calendar"></i>
                    <span class="nav-text">Randevular</span>
                </a>
            </li>


            <li>
                <a asp-controller="Message" asp-action="Index">
                    <i class="fa fa-comment"></i>
                    <span class="nav-text">Gelen Mesajlar</span>
                </a>
            </li>

            <li>
                <a asp-controller="News" asp-action="Index">
                    <i class="fa fa-tag"></i>
                    <span class="nav-text">Haberler</span>
                </a>
            </li>

            <li>
                <a asp-controller="Rooms" asp-action="Index">
                    <i class="fa fa-building"></i>
                    <span class="nav-text">Meslek Odaları</span>
                </a>
            </li>

            <li>
                <a asp-controller="Question" asp-action="Index">
                    <i class="fa fa-question"></i>
                    <span class="nav-text">Sorular-Cevaplar</span>
                </a>
            </li>

            <li>
                <a asp-controller="SubHeader" asp-action="Index">
                    <i class="fa fa-info-circle"></i>
                    <span class="nav-text">Üst Bilgi</span>
                </a>
            </li>

            <li>
                <a asp-controller="Video" asp-action="Index">
                    <i class="fa fa-play"></i>
                    <span class="nav-text">Video</span>
                </a>
            </li>

            <li>
                <a asp-controller="Default" asp-action="Index">
                    <i class="fa fa-laptop"></i>
                    <span class="nav-text">Siteye Git</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<style>
    .quixnav {
        background-color: #2c3e50;
        width: 275px;
        padding-top: 20px;
        padding-bottom: 20px;
        border-radius: 0px;
    }

    .quixnav-scroll {
        overflow-y: auto;
        max-height: 90vh;
        padding: 0 10px;
    }

    .metismenu {
        list-style: none;
        padding: 0;
        margin: 0;
    }

        .metismenu li {
            margin-bottom: 15px;
        }

        .metismenu a {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: #ecf0f1;
            font-size: 20px; /* Yazı büyütüldü */
            font-weight: 500;
            padding: 10px 15px;
            border-radius: 8px;
            transition: background-color 0.3s, transform 0.3s;
        }

            .metismenu a:hover {
                background-color: #34495e;
                transform: translateX(5px);
            }

        .metismenu i {
            margin-right: 10px;
            font-size: 24px; /* İkon da biraz büyütüldü */
        }

    .nav-label {
        font-size: 20px; /* Admin Paneli yazısı büyüklüğü korunuyor */
        font-weight: bold;
        color: #bdc3c7;
        margin-bottom: 20px;
        padding-left: 15px;
    }

</style>